<<<<<<< HEAD
name: CI

on:
  push:
    branches:
    - '*'
    tags:
      - 'v*'

jobs:
  test:
    name: Build Run UnitTests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: bash ./gradlew build jacocoTestReport sonarqube --info  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk 
  release:
    name: Release APK with Docs
    needs: apk
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk  
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: Wellcome.apk
          asset_content_type: application/zip
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build PDF
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf docs/documentation.adoc"
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF document
          path: docs/documentation.pdf
      - name: Upload Release Docs
        id: upload_release_docs
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: docs/documentation.pdf
          asset_name: documentation.pdf
          asset_content_type: application/pdf
||||||| dcf2382
=======
name: CI

on:
  push:
    branches:
    - '*'
    tags:
      - 'v*'

jobs:
  test:
    name: Build Run UnitTests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Tests
        run: bash ./gradlew build jacocoTestReport sonarqube --info  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk 
  release:
    name: Release APK with Docs
    needs: apk
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk  
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: Wellcome.apk
          asset_content_type: application/zip
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build PDF
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf documentation.adoc"
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF document
          path: documentation.pdf
>>>>>>> Feature_PhoneCall
